version: '3'

services:
  node:
    container_name: click-context-helper
    env_file: .env
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run dev
